### ISSUE TITLE
Getting error in stage 5 of pipeline in smooth.spline function.

### ISSUE THREAD

**Issue by mohammedmsk** [dphansti/mango#8]
Here is the error:
Error in smooth.spline(log10(distance_IAB_model[, 1]), distance_IAB_model[,  :
  need at least four unique 'x' values
Execution halted

Here is what the distance_IAB_model.1.text file looks like:
meanofx sumofy  pvals   sumofx  countofx
5245.5  1       0.5     5245.5  1
6540    1       0.5     6540    1

**Comment by dphansti** [comment]
Can you supply the exact command that you used to launch Mango?

**Comment by mohammedmsk** [comment]
Rscript mango/mango.R \
        --fastq1 FastqR1 \
        --fastq2 FastqR2 \
        --prefix OutFilePrefix \
        --argsfile args.txt \
        --outdir OutDir \
        --stages 1:5 || exit 1

And here is the args.txt:
bowtieref=/home/mshabb/reference/Homo_sapiens/UCSC/hg19/Sequence/BowtieIndex/genome
bedtoolsgenome=/home/mshabb/reference/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/hg19.genome
chrominclude=NULL
chromexclude=NULL
bedtoolspath=/share/apps/BEDTools/2.24.0/bin/bedtools
macs2path=/share/apps/MACS/2.0.10/bin/macs2
bowtiepath=/share/apps/bowtie/2.2.3/bin/bowtie2
linkerA=GGCCGCGATATCTTATCCAACT
linkerB=GGCCGCGATATACATTCCAACT
minlength=15
maxlength=1000
keepempty=TRUE
shortreads=FALSE
threads=16
MACS_qvalue=0.05
MACS_shiftsize=NULL
peakslop=500
peakinput=NULL
gsize=hs
distcutrangemin=1000
distcutrangemax=1000000
biascut=0.05
numofbins=50
corrMethod=BH
maxinteractingdist=1000000
FDR=0.05
extendreads=120
minPETS=2
reportallpairs=TRUE

**Comment by dphansti** [comment]
I see.  There are two things I would recommend.

1) Multi threading has been found to create errors.  I have removed the ability to multithread in the newest version of Mango.  I think that setting threads to 1 should fix your problem. I am currently working on a fix that will allow multi threading in the future.  But for now please use threads = 1.  I know that for tagmentation-generated libraries this results in a very lengthy alignment step.  I have updated the README to reflect this.  I apologize for the confusion.

2) I would recommend setting distcutrangemax to 100000.  Changing this value could also generate issues and there shouldn't be any need to change it.

Please report back to tell us if this fixed your problem.

**Comment by mohammedmsk** [comment]
So I need to run all the 5 stages again? What if I simply remove the multi-threading and run stage 5 again?

The number of reads is very high and I do not want to run mapping again.

Thanks.

**Comment by dphansti** [comment]
You don't need to run all of the stages again but unfortunately you do need to run the mapping step again as that is the stage where multi-threading applies.

**Comment by mohammedmsk** [comment]
Hello dphansti,

I re-ran the entire pipeline as recommended by you without multi-threading, unfortunately I am still getting the same error.

Attaching stdout and stderr files along with the args file.

Your help is much appreciated, thanks.

[MRRS.mango.ERG.stage5.zip](https://github.com/dphansti/mango/files/174116/MRRS.mango.ERG.stage5.zip)

**Comment by mohammedmsk** [comment]
Any update on this one?
